### ISSUE TITLE
Error wallet page

### ISSUE THREAD

**Issue by sheargwyz** [malsubrata/woo-wallet#1]
Hello. I installed this plugin, then uninstalled it last month and delete the wallet page. Then i re-installed but the page is still missing thus showing error. I can just create the page again right? Is there shortcode i can copy-paste to the wallet page?

**Comment by sheargwyz** [comment]
oops never mind. it just showed

**Comment by malsubrata** [comment]
Happy to hear from you that the issue has been resolved.
If you don't mind Can I ask you the reason why you have deleted the plugin previously.

**Comment by sheargwyz** [comment]
My website has multiple currency but the plugin doesn't support it (i mean value stay the same, even though i change the currency)

**Comment by malsubrata** [comment]
Can you please give me the reference of that plugin so that we can look into it and make compatible with that plugin.

Thank you.

**Comment by sheargwyz** [comment]
Currency Switcher for WooCommerce
https://wordpress.org/plugins/currency-switcher-woocommerce/

thank you 😊

Sent from Mail for Windows 10

**Comment by malsubrata** [comment]
Thank you very much.
