### ISSUE TITLE
Wallet is not showing if cart amount is more

### ISSUE THREAD

**Issue by rohitkriitkgp** [malsubrata/woo-wallet#14]
Wallet option is not showing in checkout page if cart amount is more. let me know if this issue has been fixed in 1.2.0 version. Thanks

**Comment by malsubrata** [comment]
@rohitkriitkgp,

This is not a bug, wallet payment method will not show if user not logged in or user don't have enough balance to process that order. In that case you can use partial payment.

**Comment by rohitkriitkgp** [comment]
@malsubrata 
I already logged in and partial payment is also enabled inside settings. But it is not showing in checkout page in UI. Thanks

**Comment by malsubrata** [comment]
Could you please share a screenshot to understand this issue.

**Comment by rohitkriitkgp** [comment]
Can you share your number if possible. I am friend of Jai Goyal.

**Comment by rohitkriitkgp** [comment]
I have attached the screenshot for both the cases. Thanks

![screen shot 2018-08-06 at 8 22 58 pm](https://user-images.githubusercontent.com/3785287/43724048-bd5332e6-99b6-11e8-8a75-4db81e622627.png)
![screen shot 2018-08-06 at 8 23 54 pm](https://user-images.githubusercontent.com/3785287/43724049-bd872146-99b6-11e8-8020-619db09e242a.png)

**Comment by malsubrata** [comment]
That is a special case I am still debug the issue on Jai Goyal server but can't find any issues yet. I request you to test WooWallet plugin on different server with default WordPress theme and WooCommerce plugin.

**Comment by rohitkriitkgp** [comment]
Okay. Thanks

**Comment by rohitkriitkgp** [comment]
Hey Subrata, I put a fix for that. But the wallet calculation is not working properly. If possible, can you check or call me on 7676453900.
