### ISSUE TITLE
Woo-Wallet

### ISSUE THREAD

**Issue by nchuan8969** [malsubrata/woo-wallet#16]
Hi Malsubrata! Good effort and plugin you have there!

But i am having trouble setting up my cashback program. when i choose cashback by percentage, it doesnt have a setting for me to set how many % i want to cashback for my customer.

Inside my product i also did not see any advance option from Woo-wallet

Would really appreciate if you can help me out with this :)

Thanks!

**Comment by malsubrata** [comment]
@nchuan8969 
You can find cash back setting from WooWallet > Settings > Credit options. Also if you set cashback product wise then you will find cashback setting tab under product data panel.

**Comment by nchuan8969** [comment]
I wanted to set a cart wise. But the cart wise didn't come out with a percentage to set.

May i know how to set it with cart amount and cash back?

Thanks


On 28 Aug 2018 4:02 PM, Subrata Mal <notifications@github.com> wrote:

@nchuan8969<https://github.com/nchuan8969>
You can find cash back setting from WooWallet > Settings > Credit options. Also if you set cashback product wise then you will find cashback setting tab under product data panel.

**Comment by malsubrata** [comment]
@nchuan8969 
![settings wordpress wordpress](https://user-images.githubusercontent.com/17632062/44714943-26783180-aad4-11e8-8173-f439094ceec0.png)
