### ISSUE TITLE
Transfer issue

### ISSUE THREAD

**Issue by geopayme** [malsubrata/woo-wallet#17]
Has anyone reported an issue with the transfer function?  The message I get is the it can not perform this action at the moment!

Thanks

**Comment by geopayme** [comment]
to be more precise the message is "the results could not be loaded"

**Comment by malsubrata** [comment]
Please check if there is any theme or plugin conflict.

**Comment by geopayme** [comment]
> Please check if there is any theme or plugin conflict.

I have been testing the plugin 4 different websites with different themes, if the theme was an issue, and I can't really figure out how to verify it since there are no errors, I should only have the issue on few of the themes not all of them.

Also on a side note, if you do development, we are connected on LinkedIn, I like to discuss a project if you are up to it.

**Comment by malsubrata** [comment]
My LinkedIn profile page URL is https://www.linkedin.com/in/subrata-mal/
