### ISSUE TITLE
Total Amount Calculation issue

### ISSUE THREAD

**Issue by RohitRD31** [malsubrata/woo-wallet#21]
If used Woowallet with smartcoupons, with cashback setting.

it gives calculation total error for product . check images.
![screenshot 68](https://user-images.githubusercontent.com/43985507/46656326-6a7a4e00-cbcb-11e8-8611-1727933a6efc.png)
![screenshot 69](https://user-images.githubusercontent.com/43985507/46656327-6a7a4e00-cbcb-11e8-9141-de71780275b6.png)

**Comment by malsubrata** [comment]
@RohitRD31 
There is an error with WooCommerce smart coupon extension. Please use below code to theme function.php file to fix that bug.
```
add_action('wp_loaded', 'remove_smart_coupon_hook', 100);
if (!function_exists('remove_smart_coupon_hook')) {

    function remove_smart_coupon_hook() {
        if (!is_admin() && class_exists('WC_Smart_Coupons')) {
            remove_action('woocommerce_after_calculate_totals', array(WC_Smart_Coupons::get_instance(), 'smart_coupons_after_calculate_totals'));
        }
    }

}
```

**Comment by RohitRD31** [comment]
Thanks ...  I Will try this and let you know.

Thanks for quick reply.

Regards,
Rohit.
Scriberr.in

**Comment by RohitRD31** [comment]
Hello Subrata,

Found a new weird bug. Please look at this.

Consider a case,
user added a product in cart , apply Wallet Credit option & Goes to checkout

Here Final total amount will be 'Cart value - Wallet credit'

On checkout he cancels the payment, And retry the payment from my account
section.

Now it will deduct wallet credit two times.

please check the attachment.

I hope u got the issue , If not please call me on 9004429039.


Regards,
Rohit Dharaskar.
(Scriberr.in)

**Comment by RohitRD31** [comment]
Hello @malsubrata ,

Recently we Enabled Coupon as cashback from woo smart coupons and saw that this above issue is back again.

Check the screenshot here we added a 100% cashback coupon upto Rs 500 and as u can see the cashback amount is added in total amount.

Please reply soon 

Regards,
Rohit.

![Screenshot (69)](https://user-images.githubusercontent.com/43985507/69144056-78014780-0af0-11ea-931c-21ee9e054632.png)
