### ISSUE TITLE
Please add a hook at woo_wallet_refund_partial_payment

### ISSUE THREAD

**Issue by webrsb** [malsubrata/woo-wallet#24]
Can you add a action hook here?
https://github.com/malsubrata/woo-wallet/blob/2a81e5011be0504f1a7a5b0dd3600cc532c46781/includes/class-woo-wallet-ajax.php#L55

Like this
https://github.com/malsubrata/woo-wallet/blob/2a81e5011be0504f1a7a5b0dd3600cc532c46781/includes/class-woo-wallet-ajax.php#L119
Thank you!

**Comment by malsubrata** [comment]
added hook `woo_wallet_partial_order_refunded`
