### ISSUE TITLE
 The balance in the admin panel is not updated.

### ISSUE THREAD

**Issue by DmitriiKudashkin** [malsubrata/woo-wallet#25]
In the admin panel in the WooWallet tab, when you click on the user's balance settings and when you enter the required amount of replenishment after clicking on the "save data" button, the error "An error has occurred, please try again" appears. What to do?

**Comment by malsubrata** [comment]
@DmitriiKudashkin 

Please deactivate the plugin and re-activate again, this might solve your issue because some time in plugin installation our dependent database tables are not created successfully.
