### ISSUE TITLE
Ordering by "Remaining balance" does not work

### ISSUE THREAD

**Issue by XjSv** [malsubrata/woo-wallet#26]
Ordering by "Remaining balance" does not seem to work in the admin panel.

It looks like the problem is in `/includes/admin/class-woo-wallet-balance-details.php` in the `prepare_items()` function. 
As I understand it, according to the documentation for [WP_User_Query](https://codex.wordpress.org/Class_Reference/WP_User_Query)  `orderby=balance` will not work even if `fields=all_with_meta` is set because the balance is not stored in the `wp_usermeta` table. 

![Imgur](https://i.imgur.com/x4K0381.png)
![Imgur](https://i.imgur.com/09OvRzZ.png)

**Comment by malsubrata** [comment]
Hi @XjSv 

Thanks for reporting this issue. We have fixed this with user meta value. Please check and let us know.
