### ISSUE TITLE
Deduction of Wallet amount twice in case of retry payment

### ISSUE THREAD

**Issue by RohitRD31** [malsubrata/woo-wallet#27]
Hello Subrata,

Found a new weird bug. Please look at this.

Consider a case,
user added a product in cart , apply Wallet Credit option & Goes to checkout

Here Final total amount will be 'Cart value - Wallet credit'

On checkout he cancels the payment, And retry the payment from my account section.

Now it will deduct wallet credit two times.

please check the attachment.

Regards, 
Rohit

![screenshot 145](https://user-images.githubusercontent.com/43985507/53548768-5625f600-3b58-11e9-9bcd-9592ea7638ce.png)

**Comment by malsubrata** [comment]
@RohitRD31 
Thanks for reporting this issue. We will check and fix in our next update and will let you know.
