### ISSUE TITLE
Balance not showing after wallet topup

### ISSUE THREAD

**Issue by marshaldudeja** [malsubrata/woo-wallet#31]
HI Support Team,

I am facing an issue on wallet topup. When a person top-ups his/her wallet, Their money is not showing in the wallet, while i got the money in my payment gateway.

- Order was generated.
- I made the order complete to check if something happens, but not fruitful.

Please let me know if i am missing something. I have attached my setting options.

Thanks!

![Screen Shot 2019-04-11 at 11 55 25 PM](https://user-images.githubusercontent.com/48507171/56085526-72f55f00-5e62-11e9-9a6f-1d2850c43564.png)
![Screen Shot 2019-04-11 at 11 55 03 PM](https://user-images.githubusercontent.com/48507171/56085527-738df580-5e62-11e9-80f7-f6b5e84e1cd9.png)
![Screen Shot 2019-04-11 at 11 54 53 PM](https://user-images.githubusercontent.com/48507171/56085528-738df580-5e62-11e9-8c2a-85427e9b762f.png)

**Comment by malsubrata** [comment]
@marshaldudeja 

Please try to deactivate the plugin and activate again and let us know.
