### ISSUE TITLE
when I click on `add` it is going to the cart page

### ISSUE THREAD

**Issue by ramaguruprakash** [malsubrata/woo-wallet#34]
When I am trying to add some 100 rupess it is going to this page.

https://drive.google.com/file/d/1AgiyJD12tOH-In237dWZ9L5aRxfdtQHR/view?usp=sharing 

not sure if I have installed a wrong version or some other plugins which is causing this issue.

**Comment by malsubrata** [comment]
Please check if the wallet rechargeable product present in your site.

**Comment by ramaguruprakash** [comment]
"wallet rechargeable" product is not present in our site. What could be the other things which I can check

**Comment by malsubrata** [comment]
Please reach out to us at support@woowallet.in regarding this.
