### ISSUE TITLE
Cashback Options not shown anymore for variable products? Intentional or regression?

### ISSUE THREAD

**Issue by dani3l3** [malsubrata/woo-wallet#38]
I can see there is a change in 1.3.10 where it appears that the admin UI has regressed for cashback and variable products? Basically the 'cashback' tab disappears for variable products.

In class-woo-wallet-admin.php 
you now set a class of "hide_if_variable" which effectively makes the TAB disappear (display: none). I see this starting with this commit https://github.com/malsubrata/woo-wallet/commit/fc73d2983b7e8cf12946a284d415ca1c14ef5fd3

My customer believes he was able to set this option also for variable products in the past, is it possible?

**Comment by malsubrata** [comment]
@dani3l3 

Yes, we remove cashback settings from variable product now you can set cashback from each variation.
![Edit product ‹ WooWallet Test — WordPress](https://user-images.githubusercontent.com/17632062/65262650-70411900-db28-11e9-813e-d3b160aa59c7.png)

**Comment by dani3l3** [comment]
Thank you!
