### ISSUE TITLE
Wallet Checkout

### ISSUE THREAD

**Issue by cyberwani** [malsubrata/woo-wallet#40]
Hello,

I am facing few issues with Terra Wallet checkout and wallet balance.

First of all, it should not display address and other fields, on the checkout page, which are not required in case of wallet recharge.

Second, when the checkout is completed, the order is waiting for the store manager's approval. If there is a setting, for each payment method, from where the administrator can set a default order-status when order is placed.

Like, if a user is using Paypal, Debit/Credit Card, or other payment methods, in which fund is transferred instantly, then order-status should be set to “completed”, or if the user is using, Check, Bank Transfer or Cash on Delivery, then order status should be set to On Hold for store manager approval.

Also, offline payment methods, like Cash, or other payment methods, which need confirmation, like Check and Bank Transfer, should be hidden by default.

**Comment by malsubrata** [comment]
@cyberwani 

Thanks for your valuable inputs, we will try to remove checkout fields for wallet recharge. Regarding the second point, you can set which payment method will be available for wallet recharge from the plugin settings page.
