### ISSUE TITLE
Allow Multiple Subscriptions in One CheckOut

### ISSUE THREAD

**Issue by boris-perisset** [malsubrata/woo-wallet#48]
We want to use the Woo-Wallet to work with our subscriptions. But at the moment only one subscription at once can be ordered.

Our subscriptions are Fresh Food Products (Vegetables, Fruits, Milk, Bread) on a weekly or monthly basis.

This Message appears now: "A subscription has been removed from your cart. Due to payment gateway restrictions, different subscription products can not be purchased at the same time."

In the WooCommerce Subscription Plugin. This could be possible.
<img width="1003" alt="Bildschirmfoto 2020-03-05 um 10 02 29" src="https://user-images.githubusercontent.com/29888458/75965072-8ff6ae80-5ec8-11ea-9b3c-fd75f1a003f5.png">

**Comment by malsubrata** [comment]
Our plugin support Mixed Checkout.
https://github.com/malsubrata/woo-wallet/blob/206f09ecdfc833ff17f7d1c00f9b876caa208d3e/includes/class-woo-wallet-payment-method.php#L18

**Comment by boris-perisset** [comment]
Ok. Thanks for your fast reply. Than i'll check my settings again...

**Comment by boris-perisset** [comment]
I'll checked it. On my Webshop it isn't working, but on a new instance with woocommerce subscription, tera wallet, storefront and astra it is working. Thanks for your time and help!

But. Damn it! Now I need to drill down the mystery whole of the Plugin Hell. Haha.
