### ISSUE TITLE
Image Post Bug

### ISSUE THREAD

**Issue by mcworks** [malsubrata/woo-wallet#5]
Hallo,
Great plugin..  I discovered a common bug across different sites with no just this plugin and woocomerce only with bare minimum themes...

When try to post/attach and "Set a Featured Image" it bugs out and doesnt allow it for some reason...\

Kindly investigate

**Comment by malsubrata** [comment]
@mcworks 
If you are using WooCommerce PayPal Express checkout plugin then please deactivate that plugin and check.

**Comment by malsubrata** [comment]
We have reported to that plugin support forum and they have solved the issue in there GitHub repository.
https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/376
