### ISSUE TITLE
TeraWallet not compatible with Dokan (multi-vendor orders)

### ISSUE THREAD

**Issue by fabiomail** [malsubrata/woo-wallet#52]
The current TeraWallet version is not calculating correctly the cashback total for orders containing products from different vendors (via Dokan). 

The cashback is calculated twice: for each sub-order as well as for the main order.

Here a video reproducing the issue with a clean installation: https://drive.google.com/file/d/1uY8VZc7mO8XDo-nJWh1zujP_k_S_1vxd/view?usp=sharing

This is a major issue that makes TeraWallet not usable with Dokan. Please urgently fix it.

**Comment by malsubrata** [comment]
Hi @fabiomail

Already posted a fix patch in your review on wordpress.org also for your reference please find attached code below and insert the code into active theme function.php file.  

```
add_filter('process_woo_wallet_general_cashback', 'process_woo_wallet_general_cashback_callback', 10, 2);

if(!function_exists('process_woo_wallet_general_cashback_callback')){
    /**
     * 
     * @param bool $process
     * @param WC_Order $order
     */
    function process_woo_wallet_general_cashback_callback($process, $order){
        if($order->get_parent_id()){
            $process = false;
        }
        return $process;
    }
}
```

**Comment by malsubrata** [comment]
@fabiomail As of now this is a temporary fix but we will add this code into our next plugin update.

**Comment by fabiomail** [comment]
@malsubrata Thank you so much for your commitment to promptly fixing this issue. I tested the code and working perfectly now!
