### ISSUE TITLE
having issue with discount plugin 

### ISSUE THREAD

**Issue by imknight** [malsubrata/woo-wallet#6]
tested with some discount plugin and it seem like the product price will revert back to original price, once deactivate woo-wallet, the price will show properly discounted price again.

**Comment by malsubrata** [comment]
@imknight 
Please share the link to that discount plugin and steps to reproduce the issue.

**Comment by imknight** [comment]
is actually a paid plugin https://codecanyon.net/item/woocommerce-dynamic-pricing-discounts/7119279

once woowallet activate any discount setting will be affected and show back to the original price.

**Comment by malsubrata** [comment]
As this is a paid plugin we can't test it along with our plugin. It will be better for us if you share plugin files so that we can test it.

**Comment by imknight** [comment]
sure , I have send the paid plugin to your email.
