### ISSUE TITLE
Update balance on Wallet

### ISSUE THREAD

**Issue by ronna88** [malsubrata/woo-wallet#64]
After add an order by REST API, the balance not updating and not showing in anywhere.
![image](https://user-images.githubusercontent.com/7954512/150353837-ceaf7b00-9511-4ed3-aa95-23fee4349b70.png)
![image](https://user-images.githubusercontent.com/7954512/150353900-cc087609-ea3a-4e68-9bf5-9c3fc4d4d93e.png)
![image](https://user-images.githubusercontent.com/7954512/150353970-94f27c7b-5c4a-46ca-b190-ad9c3a9aea57.png)

**Comment by malsubrata** [comment]
@ronna88 We have fixed this issue. Please check and let us know.

**Comment by ronna88** [comment]
![image](https://user-images.githubusercontent.com/7954512/150401615-c2ffffcc-f324-4122-82c0-dbc091e868a0.png)
![image](https://user-images.githubusercontent.com/7954512/150401646-f78d798c-2a85-4d80-926f-d90bd27f8028.png)

**Comment by malsubrata** [comment]
@ronna88 We can't understand what you want to say.

**Comment by ronna88** [comment]
sorry. you solved before
