### ISSUE TITLE
new transactions for multi customer

### ISSUE THREAD

**Issue by akbarbitaraf** [malsubrata/woo-wallet#70]
hello quys 
I want to send rows to the wallet in batches  (similar Batch update customers)
generate json  and send to api  
How do I do that?
https://....../wp-json/wc/v2/wallet/(id)

**Comment by malsubrata** [comment]
@akbarbitaraf Sorry batch upload wallet transaction via API call is not there in our core plugin. But you can write a custom endpoint using our plugin function.
