### ISSUE TITLE
Get user wallet balance by user id API Issue

### ISSUE THREAD

**Issue by wlau011** [malsubrata/woo-wallet#77]
<img width="638" alt="Terawallet API problem" src="https://user-images.githubusercontent.com/57254299/232694642-dacc74ed-79d5-44b7-8ea7-8b6adea46e35.PNG">

**Comment by malsubrata** [comment]
@wlau011 The URL should be https://example.com/wp-json/wc/v3/wallet/balance/

**Comment by wlau011** [comment]
ah my mistake @malsubrata thanks a lot for the quick reply!
