### ISSUE TITLE
Better have action menu like previous version in admin panel terawallet

### ISSUE THREAD

**Issue by rosemary112211aa** [malsubrata/woo-wallet#79]
in new design, cant see detail or transaction history from admin panel tera wallet, hope can add more feature from admin panel to view, edit, or etc

**Comment by malsubrata** [comment]
You can click on a username to view transaction history.

![image](https://github.com/malsubrata/woo-wallet/assets/17632062/f92b59df-100f-4efc-ac6d-005c19cdad37)

**Comment by rosemary112211aa** [comment]
thankyou sir,
