### ISSUE TITLE
woo wallet is not getting displayed at checkout page.

### ISSUE THREAD

**Issue by askmeswayam** [malsubrata/woo-wallet#8]
Woocommerce wallet activated and enabled as a payment option on checkout, but at checkout it's not showing for payment medium. 
website www.spidervilla.com

**Comment by askmeswayam** [comment]
Hosting has php 7.1 and latest woocommerce and wordpress

**Comment by malsubrata** [comment]
@danyaPostfactum Please make sure user has logged in and they have sufficient balance to their account to process the order.

**Comment by askmeswayam** [comment]
Alright

Got the fix. Thanks for the super fast response.

**Comment by SoHighSpiral** [comment]
am facing similar issue. woowallet used to worked well but after resetting it didnt show up in check out page

**Comment by malsubrata** [comment]
Please check if wallet payment method active in WooCommerce > settings > payment tab.

**Comment by seanchenxi** [comment]
Hi, @malsubrata, I'm facing similar issue with the latest version of plugin, wordpress 5.5 and woocommerce 4.4.1. wallet payment option is not shown in checkout page.
I checked WooCommerce > settings > payment tab, it is enabled.
I checked user balance, it is positive. 
Can u have other check points to verify ? 
Thanks

**Comment by seanchenxi** [comment]
Juste for information. 
We've found the reason. Because we have un activated B2B plugin who added more payment rules and blocked this new payment method.
