### ISSUE TITLE
I HAVE A WOO WALLET SITE AND CHECKOUT PAGE IS NOT DISPLAYING. WHENEVER I GOTO ADD FUND AND ENTER AMMOUNT AND CLICK PROCEED IT REDIRECTS TO HOMEPAGE

### ISSUE THREAD

**Issue by adilmeh-12** [malsubrata/woo-wallet#81]
I HAVE A WOO WALLET SITE AND CHECKOUT PAGE IS NOT DISPLAYING. WHENEVER I GOTO ADD FUND AND ENTER AMMOUNT AND CLICK PROCEED IT REDIRECTS TO HOMEPAGE. WHAT CAN I DO

**Comment by malsubrata** [comment]
@adilmeh-12 Please let us know if you can add other products to the cart and proceed to the checkout page.
