### ISSUE TITLE
Terawallet balance is not deducting

### ISSUE THREAD

**Issue by Rkoppalap** [malsubrata/woo-wallet#83]
Im allowing customers to oder with wallet balance and remaining extra amount with other payment options. After successful order the wallet balance is still the same.

**Comment by Rkoppalap** [comment]
Please find below screenshot for reference 
![IMG_0038](https://github.com/malsubrata/woo-wallet/assets/159767131/4bc4cb5f-2e2f-454d-8c13-e397a1a6da17)
![IMG_0039](https://github.com/malsubrata/woo-wallet/assets/159767131/fe3678fd-4c20-4053-ad28-6e7540c976d4)

**Comment by xtheonexuk** [comment]
What was the solution for this? I have this issue now!
