### ISSUE TITLE
Topup report slows down admin panel

### ISSUE THREAD

**Issue by Parviz-Elite** [malsubrata/woo-wallet#87]
File path: **wp-content/plugins/woo-wallet/includes/class-woo-wallet-admin.php**
Method name: **add_wallet_topup_report**

in my case it's run about 70,000 queries. i think **get_wallet_rechargeable_orders** ignores date query and try to fetch all wallet recharge order ids. i disabled this method for now.

![Untitled](https://github.com/user-attachments/assets/11618fae-dd68-4330-9ec3-807ffe1daccb)

**Comment by malsubrata** [comment]
@Parviz-Elite We fix this issue here please download and install the plugin from here and let us know.

**Comment by Parviz-Elite** [comment]
Hi, the problem is solved!

Thank you for your efforts.
