### ISSUE TITLE
Plugin dashboard disappeared (404 Error)

### ISSUE THREAD

**Issue by madhusudan81** [malsubrata/woo-wallet#9]
Hi,

I updated the latest version of woocommerce wallet and the plugin dashboard disappeared and is showing 404 error. 

Here is the attached screenshot.

p.s. The portal where it is integrated, it is a non profit initiative.
![screenshot](https://user-images.githubusercontent.com/22044670/40929236-ca12c61e-6841-11e8-93ec-fc9a72d9a051.jpg)

**Comment by malsubrata** [comment]
Update permalink structure from settings>permalink. Just hit the save changes button.

**Comment by madhusudan81** [comment]
Thank you, it fixed it..
